puppycompanyblog/blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField , SubmitField , TextAreaField
from wtforms.validators import DataRequired
from flask_wtf.file import FileField, FileAllowed

class BlogPostForm(FlaskForm):
    title = StringField('Title',validators=[DataRequired()])
    text = TextAreaField('Text',validators=[DataRequired()])
    picture = FileField('投稿する写真を選択してください', validators=[
                        FileAllowed(['jpg', 'png'])])
    submit = SubmitField("Post")

puppycompanyblog/blog_posts/views.py
from flask import render_template , url_for , flash , request , redirect , Blueprint
from flask_login import current_user , login_required
from puppycompanyblog import db
from puppycompanyblog.models import BlogPost
from puppycompanyblog.blog_posts.forms import BlogPostForm

# blog_postsブループリントを作成
# ここで作成した関数にはurl_for(blog_posts.関数)のリンクで飛ぶことができる
blog_posts = Blueprint('blog_posts',__name__)

# blog_postsブループリントをappに実装することで/createにアクセスするとここへリンクされる
# url_for(blog_posts.create_post)をすることでアクセスでき、リンクは/createになる。
@blog_posts.route('/create',methods=['GET','POST'])
# 認証したいページの場合に記述
@login_required
def create_post():
    
    # BlogPostFormを配置
    form = BlogPostForm()
    
    # submitボタンが押された場合
    if form.validate_on_submit():
        #form.title.dataのようにフォームに入力された値を取り出す
        # models.pyのBlogPostデータベースモデルのインスタンスを作成する
        blog_post = BlogPost(title=form.title.data,
                             text=form.text.data,
                             user_id=current_user.id)
        
        db.session.add(blog_post)
        db.session.commit()
        flash('Blog Post Created')
        # redirectは別のurlへ飛ばす
        # ここではcoreブループリントのindex関数へ飛ばす
        return redirect(url_for('core.index'))
    # create_post.htmlを表示する。BlogPostForm()のformインスタンスを渡して入力してもらう
    return render_template('create_post.html',form=form)



@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
    # データベースにアクセスしてなかったら404を返す
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    # データベースから帰ってきたblog_postのtitleなどを渡す
    return render_template('blog_post.html',
                           title=blog_post.title,
                           date=blog_post.date,
                           post=blog_post
                           )
    
    
    
@blog_posts.route('/<int:blog_post_id>/update',methods=['GET','POST'])
@login_required
def update(blog_post_id):
    # ない場合は404を返す
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    
    # 更新する人が作成者かどうか
    # current_userはlogin_managerの属性、現在ログインしているユーザー名が入っている
    # blog_post.authorは投稿したpostの作成者
    if blog_post.author != current_user:
        abort(403)
        
    form = BlogPostForm()
    
    if form.validate_on_submit():
    
        blog_post.title = form.title.data
        blog_post.text = form.text.data
        db.session.commit()
        flash('Blog Post Updated')
        return redirect(url_for('blog_posts.blog_post',blog_post_id=blog_post.id))
    
    # updateしなかった場合
    # form.title.data = blog_post.titleフォームに現在の状態を表示する
    elif request.method == 'GET':
        form.title.data = blog_post.title
        form.text.data = blog_post.text
        
    return render_template('create_post.html',title='Updating',form=form)



@blog_posts.route('/<int:blog_post_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_post(blog_post_id):
    # ない場合は404を返す
    blog_post = BlogPost.query.get_or_404(blog_post_id)

    # 更新する人が作成者かどうか
    if blog_post.author != current_user:
        abort(403)
    
    db.session.delete(blog_post)
    db.session.commit()
    flash('Blog Post Deleted')
    return redirect(url_for('core.index'))
    

puppycompanyblog/users/views.py
from flask import render_template , url_for , flash , redirect , request , Blueprint
from flask_login import login_user , current_user , logout_user , login_required
from puppycompanyblog import db
from puppycompanyblog.models import User , BlogPost
from puppycompanyblog.users.forms import RegistrationForm , LoginForm , UpdateUserForm
from puppycompanyblog.users.picture_handler import add_profile_pic
from datetime import datetime

users = Blueprint('users', __name__)

# register
@users.route('/register',methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    
    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)
        
        db.session.add(user)
        db.session.commit()
        flash('Thanks for registration!')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)


# Login
@users.route('/login', methods=['GET','POST'])
def login():
    
    form = LoginForm()
    
    if form.validate_on_submit():
        # フィルターをかけて検索して最初に見つかったものを返す
        user = User.query.filter_by(email=form.email.data).first()
        
        # userがあるか、パスワードが合っているか
        if user is not None and user.check_password(form.password.data):
            login_user(user)
            flash('Log in Success!')
            
            next = request.args.get('next')
            
            if next == None or not next[0] == '/':
                next = url_for('core.index')
            
            return redirect(next)
    return render_template('login.html',form=form)
        

# Logout
# url_for('users/logout')
@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for("core.index"))

# url_for('users.account')かhtmlからは{{url_for('users.account')}}でここへ飛ぶことができる
@users.route('/account',methods=['GET','POST'])
# 認証したいページに @ login_required デコレートする
@login_required
def account():
    form = UpdateUserForm()
    if form.validate_on_submit():
        
        #画像がセットされているか
        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic
        
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated!')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    
    now = datetime.now()
    epochtime = str(now.timestamp())
    profile_image = url_for('static', filename='profile_pics/' +
                            current_user.profile_image)+"?"+epochtime
    return render_template('account.html',profile_image=profile_image,form=form,epochtime=epochtime)

# url_for('/<username>')
@users.route('/<username>')
def user_posts(username):
    page = request.args.get('page',1,type=int)
    # user情報を持ってくる
    user = User.query.filter_by(username=username).first_or_404()
    # 今まで投稿したブログを表示する
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page,per_page=5)
    now = datetime.now()
    epochtime = str(now.timestamp())
    return render_template('user_blog_posts.html', blog_posts=blog_posts, user=user, epochtime=epochtime)

puppycompanyblog/templates/account.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
        <div align="center">
            <h1>welcom to the page for {{current_user.username}}</h1>
            <img align="center" src="{{url_for('static',filename='profile_pics/' + current_user.profile_image)}}?{{epochtime}}">
        </div>
    </div>

    <div class="container">
        <!--excelやpngファイルを表示するときはaction="" enctype="multipart/form-data"が必要-->
        <form method="POST" action="" enctype="multipart/form-data">
            {{form.hidden_tag()}}

            <div class="form-group">
                {{form.username.label(class="form-control-label")}}
                {{form.username(class="form-control form-control-lg")}}
            </div>

            <div class="form-group">
                {{form.email.label(class="form-control-label")}}
                {{form.email(class="form-control form-control-lg")}}
            </div>
            

            <div class="form-group">
                {{form.picture.label(class="form-control-label")}}
                {{form.picture(class="form-control form-control-lg")}}
            </div>


            <div class="form-group">
                {{form.submit(class="btn btn-outline-info")}}
            </div>
            
            

        </form>
    </div>
{% endblock %}

puppycompanyblog/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">
    <title>書き込み投稿サイト</title>

    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    
    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
</head>


<body>
    <ul class="nav">
        <li class="nav-link">
            <!--coreブループリントのindex関数-->
            <a href="{{url_for('core.index')}}">Home</a>
        </li>
        <li class="nav-link">
            <!--coreブループリントのinfo関数-->
            <a href="{{url_for('core.info')}}">About</a>
        </li>

        <!--ユーザーがログインしている場合-->
        <!--current_userはlogin_managerの属性-->
        {% if current_user.is_authenticated %}
        <li class="nav-link">
            <!--usersブループリントのlogout関数-->
            <a href="{{url_for('users.logout')}}">Log Out</a>
        </li>
        <li class="nav-link">
            <a href="{{url_for('users.account')}}">アカウント</a>
        </li>
        <li class="nav-link">
            <a href="{{url_for('blog_posts.create_post')}}">投稿</a>
        </li>

        <!--ユーザーがログインしていない場合-->
        {% else %}
        <li class="nav-link">
            <a href="{{url_for('users.login')}}">Log In</a>
        </li>
        <li class="nav-link">
            <a href="{{url_for('users.register')}}">登録</a>
        </li>
        {% endif %}
    </ul>

    <div class="container">
        {% block content %}
        data
        {% endblock %}
    </div>
        

    
</body>
</html>

puppycompanyblog/templates/blog_post.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
        <h1>{{post.title}}</h1>
        <h2>Written by: {{post.author.username}}</h2>
        <h3>Published: {{post.date.strftime("%Y-%m-%d %H:%M:%S")}}</h3>
        <!--
            <img src="/static/profile_pics/one.png" class="rounded float-left" alt="">
        -->
        
        <p>{{post.text}}</p>

        {% if post.author == current_user %}
        <div>
            <a href="{{url_for('blog_posts.update',blog_post_id=post.id)}}">Update</a>
            <button type="button" class="btn btn-danger" data-toggle='modal' data-target="#del_modal">Delete</button>
        </div>
        
        {% endif %}
    </div>


    <div class="modal" tabindex="-1" role="dialog" id="del_modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Delete Post?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to delete the post?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

                    <form action="{{url_for('blog_posts.delete_post',blog_post_id=post.id)}}" method="post">
                        <input class="btn btn-danger" type="submit" value="Delete">
                    </form>
                    
                </div>
            </div>
        </div>
    </div>
{% endblock %}

puppycompanyblog/templates/create_post.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <form class="form-group" method="POST">
            {{form.hidden_tag()}}

            <div class="form-group">
                {{form.title.label(class="form-control-label")}}
                {{form.title(class="form-control form-control-lg")}}
            </div>
            <div class="form-group">
                {{form.text.label(class="form-control-label")}}
                {{form.text(class="form-control form-control-lg")}}
            </div>
            <div class="form-group">
                {{form.submit(class="btn btn-outline-info")}}
            </div>
        </form>
    </div>
{% endblock %}

puppycompanyblog/templates/index.html
{% extends "base.html" %}
{% block content %}
    <!--jumbotron は左右に広げて配置する-->
    <div class="jumbotron">
        <h1>書き込み投稿サイト</h1>
    </div>

    <!--containerは中身をセンタリングし幅を固定する-->
    <div class="container">
        <!--blog_postsをフォームから渡している。過去のブログのリスト-->
        <!--postオブジェクトの属性はmodels.pyのBlogPostクラスに記述している-->
        {% for post in blog_posts.items %}
            <div class="card">
                <div class="card body">
                    <!--blog_posts.blog_postはblog_postsBlueprintのblog_post関数-->
                    <!--__init__.pyでBlueprintをappに結びつけることでリンクしている-->
                    <!--blog_post_id=post.idはblog_post関数の引数-->
                    <!--post.author.usernameはpostを作成したもの、modles.pyのUserクラスに記述している-->
                    <h2> Title: <a class="card-title" href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">{{post.title}}</a></h2>
                    <h5> Written by: <a href="{{url_for('users.user_posts',username=post.author.username)}}">{{post.author.username}}</a></h5>
                    <p>  Create time: {{post.date.strftime("%Y-%m-%d %H:%M:%S")}}</p>
                    <!--
                        formで画像取得→pythonで200かけ200にしディレクトリ作成、画像保存、/staticからのパスを返す
                        <img src="/static/profile_pics/one.png" class="rounded float-left" alt="">
                    -->
                    
                    <a class="btn btn-primary" href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">Read Blog Post</a>
                    
                    
                    
                </div>
            </div>
        
        {% endfor %}
    </div>


    <!--Page Navigation exampleはページのリンクを数字で表す-->
    <nav aria-label='Page Navigation example'>
        <ul class="pagination justify-content-center">
            {% for page_num in blog_posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
            <!--現在の参照しているページのリンクならば-->
            {% if blog_posts.page == page_num %}
            <li class="page-item disabled">
                <!--coreブループリントのindex関数-->
                <a class="page-link" href="{{url_for('core.index',page=page_num)}}">{{page_num}}</a>
            </li>
            {% else %}
            <li class="page-item">
                <!--coreブループリントのindex関数-->
                <a class="page-link" href="{{url_for('core.index',page=page_num)}}">{{page_num}}</a>
            </li>
            {% endif %}
    
            {% endfor %}
        </ul>
    </nav>


{% endblock %}

puppycompanyblog/templates/info.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
        <h1>まだ書く内容がありません</h1>
    </div>
{% endblock %}

puppycompanyblog/templates/login.html
{% extends "base.html" %}
{% block content %}
    <form class="form-group" method="POST">
        {{form.hidden_tag()}}

        <div class="form-group">
            {{form.email.label(class="form-control-label")}}
            {{form.email(class="form-control form-control-lg")}}<br>
        </div>
        
        <div class="form-group">
            {{form.password.label(class="form-control-label")}}
            {{form.password(class="form-control form-control-lg")}}<br>
        </div>

        <div class="form-group">
            {{form.submit(class="btn btn-outline-info")}}
        </div>

        
    </form>
{% endblock %}

puppycompanyblog/templates/register.html
{% extends "base.html" %}
{% block content %}
    <form class="form-group" method="POST">
        {{form.hidden_tag()}}
        <div class="form-group">
            {{form.email.label(class="form-control-label")}}
            {{form.email(class="form-control form-control-lg")}}<br>
        </div>
        
        <div class="form-group">
            {{form.username.label(class="form-control-label")}}
            {{form.username(class="form-control form-control-lg")}}<br>
        </div>
        
        <div class="form-group">
            {{form.password.label(class="form-control-label")}}
            {{form.password(class="form-control form-control-lg")}}<br>
        </div>
        
        <div class="form-group">
            {{form.pass_confirm.label(class="form-control-label")}}
            {{form.pass_confirm(class="form-control form-control-lg")}}<br>
        </div>
        
        <div class="form-group">
            {{form.submit(class="btn btn-outline-info")}}
        </div>
        
    </form>
{% endblock %}

puppycompanyblog/templates/user_blog_posts.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <div class="jumbotron">
            <div align='center'>
                <h1>welcome to the page for {{user.username}}</h1>
                <img src="{{url_for('static',filename='profile_pics/'+ user.profile_image)}}?{{epochtime}}">
            </div>
        </div>
    

    {% for post in blog_posts.items %}

        <h2><a href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">{{post.title}}</a></h2>
        Written By: <a href="{{url_for('users.user_posts',username=post.author.username)}}">{{post.author.username}}</a>
        <p class="text-muted">Published on: {{post.date.strftime("%Y-%m-%d %H:%M:%S")}}</p>
        <br>
        <!--
            <img src="/static/profile_pics/one.png" class="rounded float-left" alt="">
        -->
        
        <br>
        <p>{{post.text}}</p>
        <br>
    {% endfor %}
    </div>



    <nav aria-label='Page Navigation example'>
        <ul class="pagination justify-content-center">
            {% for page_num in blog_posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
                {% if blog_posts.page == page_num %}
                    <li class="page-item disabled">
                        <a class="page-link" href="{{url_for('users.user_posts',username=user.username,page=page_num)}}">{{page_num}}</a>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="{{url_for('users.user_posts',username=user.username,page=page_num)}}">{{page_num}}</a>
                    </li>
                {% endif %}
            
            {% endfor %}
        </ul>
    </nav>


    
{% endblock %}